name: Tachyon
options:
  bundleIdPrefix: com.tachyon
  deploymentTarget:
    macOS: "13.0"
  
targets:
  Tachyon:
    type: application
    platform: macOS
    sources:
      - Sources/Tachyon
    resources:
      - Resources
    info:
      path: Resources/Info.plist
      properties:
        LSUIElement: true
        CFBundleShortVersionString: "0.1.0"
        CFBundleVersion: "1"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.tachyon.app
      PRODUCT_NAME: Tachyon
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "13.0"
      ENABLE_HARDENED_RUNTIME: YES
      CODE_SIGN_IDENTITY: "Apple Development"
      CODE_SIGN_ENTITLEMENTS: Sources/Tachyon/Tachyon.entitlements
    dependencies:
      - target: TachyonCore
  
  TachyonCore:
    type: framework
    platform: macOS
    sources:
      - path: Sources/Tachyon
        excludes:
          - App
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.tachyon.core
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "13.0"
  
  TachyonTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests/TachyonTests
    dependencies:
      - target: TachyonCore
    settings:
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "13.0"
